sudo: false
language: python

python:
  - "3.5"
  - "3.6"

install:
  - pip install flake8
  - pip install pytest-cov
  - pip install coveralls
  - pip install -e .

script:
  - flake8 aiohttp_basicauth tests
  - pytest --cov=./aiohttp_basicauth tests/

after_success:
  - coveralls

cache:
  directories:
    - $HOME/.cache/pip

notifications:
  email: false
